
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;



ALTER TABLE `clients` ADD `flight_number` VARCHAR(255) NULL AFTER `e_mail`, ADD `pickup` VARCHAR(255) NULL AFTER `flight_number`, ADD `dropoff` VARCHAR(255) NULL AFTER `pickup`;
ALTER TABLE `invoices` ADD `sale` INT NULL AFTER `vehicle_status`;